// The 24 premade baskets: 12 for her, 12 for him, three per price tier.
// Each item links to an Amazon search filtered around its price (see app.js),
// so links never go stale the way hard-coded product IDs do.
// Fields: n = item name, q = Amazon search phrase, p = approximate price in USD.

window.TIERS = [
  { id: 1, label: "Under $50" },
  { id: 2, label: "$50 to $100" },
  { id: 3, label: "$100 to $250" },
  { id: 4, label: "$250 and up" },
];

window.BASKETS = [
  // ---------- FOR HER ----------
  { id: "her-cozy-night", for: "her", tier: 1, name: "Cozy Night In",
    blurb: "Soft things for the couch and a slower evening.",
    items: [
      { n: "Fuzzy sherpa socks", q: "fuzzy sherpa socks women", p: 12 },
      { n: "Lavender soy candle", q: "lavender soy candle", p: 15 },
      { n: "Herbal tea sampler", q: "herbal tea sampler gift box", p: 12 },
      { n: "Silk sleep mask", q: "silk sleep mask", p: 10 },
    ] },
  { id: "her-self-care", for: "her", tier: 1, name: "Self-Care Sunday",
    blurb: "A bathroom-shelf reset she can use the same day.",
    items: [
      { n: "Sheet mask set", q: "korean sheet mask set", p: 14 },
      { n: "Rose quartz face roller", q: "rose quartz face roller gua sha set", p: 12 },
      { n: "Bath bomb gift set", q: "bath bomb gift set", p: 13 },
      { n: "Silk scrunchies", q: "mulberry silk scrunchies", p: 10 },
    ] },
  { id: "her-bookworm", for: "her", tier: 1, name: "The Bookworm",
    blurb: "For the one who reads past midnight.",
    items: [
      { n: "Rechargeable book light", q: "rechargeable clip on book light", p: 15 },
      { n: "Reading journal", q: "reading journal book log", p: 14 },
      { n: "Leather bookmarks", q: "leather bookmark set", p: 8 },
      { n: "Bookish ceramic mug", q: "book lover ceramic mug", p: 10 },
    ] },
  { id: "her-spa-day", for: "her", tier: 2, name: "Spa Day at Home",
    blurb: "Robe on, phone off.",
    items: [
      { n: "Plush waffle robe", q: "plush waffle robe women", p: 40 },
      { n: "Aromatherapy diffuser", q: "ceramic aromatherapy diffuser", p: 25 },
      { n: "Essential oil set", q: "essential oil gift set", p: 15 },
      { n: "Bath pillow", q: "bath pillow spa", p: 18 },
    ] },
  { id: "her-morning-ritual", for: "her", tier: 2, name: "Morning Ritual",
    blurb: "Better coffee, made slowly.",
    items: [
      { n: "Pour-over coffee set", q: "pour over coffee maker set glass", p: 35 },
      { n: "Specialty whole bean coffee", q: "specialty whole bean coffee gift", p: 18 },
      { n: "Handmade ceramic mug", q: "handmade ceramic coffee mug", p: 16 },
      { n: "Handheld milk frother", q: "handheld milk frother", p: 15 },
    ] },
  { id: "her-garden", for: "her", tier: 2, name: "Garden Girl",
    blurb: "Everything for a windowsill or a backyard plot.",
    items: [
      { n: "Indoor herb garden kit", q: "indoor herb garden kit", p: 25 },
      { n: "Ceramic planters", q: "ceramic planter set with drainage", p: 25 },
      { n: "Floral gardening gloves", q: "floral gardening gloves women", p: 15 },
      { n: "Pruning shears", q: "pruning shears garden", p: 15 },
    ] },
  { id: "her-wellness", for: "her", tier: 3, name: "Wellness Reset",
    blurb: "For the morning workout and the recovery after.",
    items: [
      { n: "Premium yoga mat", q: "premium non slip yoga mat", p: 70 },
      { n: "Mini massage gun", q: "mini massage gun", p: 60 },
      { n: "Insulated water bottle", q: "insulated stainless water bottle 32 oz", p: 35 },
      { n: "Resistance band set", q: "fabric resistance bands set", p: 25 },
    ] },
  { id: "her-kitchen", for: "her", tier: 3, name: "Kitchen Muse",
    blurb: "Pieces a home cook will use every week.",
    items: [
      { n: "Enameled Dutch oven", q: "enameled cast iron dutch oven", p: 90 },
      { n: "Olive oil gift set", q: "olive oil gift set", p: 30 },
      { n: "Linen apron", q: "linen apron women", p: 25 },
      { n: "Olive wood spoon set", q: "olive wood spoon set", p: 20 },
    ] },
  { id: "her-jet-setter", for: "her", tier: 3, name: "Jet Setter",
    blurb: "Packed light, sounding good.",
    items: [
      { n: "Noise-cancelling earbuds", q: "noise cancelling wireless earbuds", p: 120 },
      { n: "Packing cubes", q: "packing cubes set", p: 30 },
      { n: "Leather passport holder", q: "leather passport holder women", p: 25 },
      { n: "Travel jewelry case", q: "travel jewelry case", p: 20 },
    ] },
  { id: "her-luxe-glow", for: "her", tier: 4, name: "Luxe Glow",
    blurb: "The beauty upgrades she wouldn't buy herself.",
    items: [
      { n: "LED light therapy mask", q: "led light therapy face mask", p: 180 },
      { n: "Luxury skincare set", q: "luxury skincare gift set", p: 90 },
      { n: "Mulberry silk pillowcase", q: "mulberry silk pillowcase", p: 60 },
    ] },
  { id: "her-cashmere", for: "her", tier: 4, name: "Cashmere & Calm",
    blurb: "Quiet luxury for the evenings.",
    items: [
      { n: "Cashmere wrap", q: "cashmere wrap scarf women", p: 150 },
      { n: "Silk pajama set", q: "silk pajama set women", p: 100 },
      { n: "Luxury scented candle", q: "luxury scented candle", p: 70 },
    ] },
  { id: "her-moments", for: "her", tier: 4, name: "Capture Every Moment",
    blurb: "Photos she can hold, and a frame for the rest.",
    items: [
      { n: "Digital photo frame", q: "wifi digital photo frame", p: 160 },
      { n: "Instant camera", q: "instant camera", p: 140 },
      { n: "Instant film pack", q: "instant film twin pack", p: 40 },
      { n: "Linen photo album", q: "linen photo album", p: 30 },
    ] },

  // ---------- FOR HIM ----------
  { id: "him-grill-starter", for: "him", tier: 1, name: "Grill Master Starter",
    blurb: "The basics for a backyard weekend.",
    items: [
      { n: "BBQ grill tool set", q: "bbq grill tool set", p: 20 },
      { n: "BBQ rub sampler", q: "bbq rub gift set", p: 14 },
      { n: "Instant-read meat thermometer", q: "instant read meat thermometer", p: 14 },
    ] },
  { id: "him-coffee", for: "him", tier: 1, name: "Coffee Snob",
    blurb: "Fresh grounds, his way.",
    items: [
      { n: "Manual burr grinder", q: "manual burr coffee grinder", p: 25 },
      { n: "Whole bean coffee sampler", q: "whole bean coffee sampler gift", p: 20 },
    ] },
  { id: "him-game-night", for: "him", tier: 1, name: "Game Night",
    blurb: "For the friend who always hosts.",
    items: [
      { n: "Poker chip set", q: "poker chip set case", p: 25 },
      { n: "Party card game", q: "party card game adults", p: 20 },
    ] },
  { id: "him-whiskey-den", for: "him", tier: 2, name: "Whiskey Den",
    blurb: "A proper pour, properly chilled.",
    items: [
      { n: "Whiskey decanter", q: "whiskey decanter", p: 35 },
      { n: "Crystal rocks glasses", q: "crystal whiskey glasses set", p: 30 },
      { n: "Whiskey stones", q: "stainless whiskey stones", p: 18 },
    ] },
  { id: "him-desk", for: "him", tier: 2, name: "Desk Upgrade",
    blurb: "A tidier, better-lit place to work.",
    items: [
      { n: "Leather desk mat", q: "leather desk mat", p: 30 },
      { n: "Wireless charging stand", q: "wireless charging stand", p: 30 },
      { n: "LED desk lamp", q: "led desk lamp", p: 20 },
      { n: "Cable organizer", q: "desk cable organizer", p: 12 },
    ] },
  { id: "him-camper", for: "him", tier: 2, name: "Weekend Camper",
    blurb: "Gear that earns its spot in the pack.",
    items: [
      { n: "Multitool", q: "multitool pliers", p: 40 },
      { n: "Camping hammock", q: "camping hammock with straps", p: 25 },
      { n: "Rechargeable headlamp", q: "rechargeable headlamp", p: 20 },
      { n: "Enamel camp mug", q: "enamel camp mug", p: 15 },
    ] },
  { id: "him-barbershop", for: "him", tier: 3, name: "Barbershop at Home",
    blurb: "A clean shave or a sharp beard, his call.",
    items: [
      { n: "Beard trimmer", q: "beard trimmer men", p: 70 },
      { n: "Beard grooming kit", q: "beard grooming kit", p: 35 },
      { n: "Safety razor", q: "double edge safety razor", p: 30 },
      { n: "Shaving brush and soap set", q: "shaving brush soap set", p: 25 },
    ] },
  { id: "him-home-bar", for: "him", tier: 3, name: "Home Bar Pro",
    blurb: "Shake, stir, and serve like he means it.",
    items: [
      { n: "Cocktail shaker set", q: "cocktail shaker bartender kit", p: 45 },
      { n: "Cocktail bitters set", q: "cocktail bitters gift set", p: 30 },
      { n: "Rocks glasses", q: "rocks glasses set", p: 30 },
      { n: "Large ice cube molds", q: "large ice cube mold", p: 20 },
      { n: "Cocktail recipe book", q: "cocktail recipe book", p: 25 },
    ] },
  { id: "him-recovery", for: "him", tier: 3, name: "Recovery Kit",
    blurb: "For the guy who never skips leg day.",
    items: [
      { n: "Massage gun", q: "percussion massage gun", p: 100 },
      { n: "Duffel gym bag", q: "gym duffel bag men", p: 50 },
      { n: "Foam roller", q: "foam roller", p: 30 },
      { n: "Shaker bottle", q: "protein shaker bottle", p: 15 },
    ] },
  { id: "him-audiophile", for: "him", tier: 4, name: "The Audiophile",
    blurb: "Records, played right.",
    items: [
      { n: "Belt-drive turntable", q: "belt drive turntable", p: 200 },
      { n: "Powered bookshelf speakers", q: "powered bookshelf speakers", p: 150 },
      { n: "Vinyl storage crate", q: "vinyl record storage crate", p: 40 },
      { n: "Record cleaning kit", q: "vinyl record cleaning kit", p: 25 },
    ] },
  { id: "him-pitmaster", for: "him", tier: 4, name: "Pitmaster",
    blurb: "Low and slow, with tools that last.",
    items: [
      { n: "Chef knife set", q: "chef knife set", p: 120 },
      { n: "Wireless smart meat thermometer", q: "wireless smart meat thermometer", p: 100 },
      { n: "Butcher block board", q: "end grain butcher block cutting board", p: 70 },
      { n: "Cast iron griddle", q: "cast iron griddle", p: 60 },
      { n: "Smoking wood chips", q: "smoking wood chips variety", p: 25 },
    ] },
  { id: "him-carry", for: "him", tier: 4, name: "Gentleman's Carry",
    blurb: "What goes in his pockets every day.",
    items: [
      { n: "Automatic watch", q: "automatic watch men", p: 200 },
      { n: "Leather bifold wallet", q: "full grain leather bifold wallet", p: 60 },
      { n: "Key organizer", q: "leather key organizer", p: 25 },
    ] },
];
